#!/usr/bin/dumb-init /bin/sh
TAIL_LOG=/var/log/tinyproxy/tinyproxy.log

echo "`date` Starting `tinyproxy -v` service..."
tinyproxy

echo "`date` Tailing Tinyproxy log..."
while ! tail -f $TAIL_LOG ; do sleep 1 ; done